version: '3'
services: 
  tomcat1: &was
    build: 
      context: .
      args: 
        conf: tomcat1/conf
        warpath: tomcat1/webapps/jpetstore.war
      dockerfile: ./DockerfileTomcat
    volumes: 
      - ./tomcat1/logs/:/usr/local/tomcat/logs/
  
  tomcat2:
    <<: *was
    build: 
      context: .
      args: 
        conf: tomcat2/conf
        warpath: tomcat2/webapps/jpetstore.war
      dockerfile: ./DockerfileTomcat
    volumes:
      - ./tomcat2/logs/:/usr/local/tomcat/logs/
    
  nginx:
    build: 
      context: .
      dockerfile: ./DockerfileNginx
      args: 
        conf: nginx/conf
    ports: 
      - "80:80"

networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: 1496
